Ember optional
chancancode/ember-bench pull request #10
Opened 2016-09-15 00:28 UTC by iezer

2nd commit makes ember and glimmer optional based on if they are in the config. Probably not a great long term solution but for now it works for both of our use cases. Merge after #9

2016-09-29 21:48 UTC, rwjblue requested changes
Looking good!  I submitted #11 which is complementary to this (allows building Ember without building a custom Glimmer).

2016-09-29 21:48 UTC, rwjblue commented on lib/utils.rb
> +    @custom_ember_glimmer ||= experiments.all? { |e| e["ember"] && e["glimer"] }
Lets base this off of `e['ember']` only, inside the `build_ember` script I am going to make the glimmer build optional separately

2016-10-11 15:27 UTC, iezer commented on lib/utils.rb
> +    @custom_ember_glimmer ||= experiments.all? { |e| e["ember"] && e["glimer"] }
I made this change and also updated the README.md which reflects this and your other PR #11

2017-02-11 01:39 UTC, closed without merging

2017-02-11 01:40 UTC, rwjblue commented
Thanks @iezer!  We merged this in https://github.com/chancancode/ember-bench/commit/312fdd5c500f5b5d343ad0e14b20f765a0a36fb3....